services:
  - type: worker
    name: telegram-bot-worker
    runtime: python
    plan: starter   # أو free حسب حسابك
    region: frankfurt
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
